### Make a Nginx pod with 80 port which is accessible by a service in the cluster with 8080 port and externally 30012.
### Make a redis pod with 6379 port which is accessible by a service in the cluster with 8081 port and externally 30013.

---
apiVersion: v1
kind: Pod
metadata:
  name: web-and-db
  labels:
    web: nginx
    db: redis
spec:
  containers:
    - name: nginx-container
      image: nginx
      imagePullPolicy: Always
      ports:
        - containerPort: 80

    - name: redis-container
      imagePullPolicy: Always
      image: redis
      ports:
        - containerPort: 6379

  restartPolicy: Always


---
apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
  labels:
    service: nodeport
spec:
  selector:
    web: nginx
    db: redis
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 30012
      name: webport

    - port: 8081
      targetPort: 6379
      nodePort: 30013
      name: dbport

  type: NodePort
  clusterIP: 10.96.0.71
