### Make multiple internal and external services for communicating each others and from outside cluster where internal port is 8080, external port is 30012 and container port 80
### And internal port is 9090, external port 30013 and container port 5432.

---
apiVersion: v1
kind: Service
metadata:
  name: nodeportservices
  labels:
    services: multiserices
spec:
  selector:
    app: webapp
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30012
      name: webport
    - port: 5432
      targetPort: 9090
      nodePort: 30013
      name: dbport
  type: NodePort
  clusterIP: 10.96.0.71