### Make a deployment of Nginx with 80 port which is accessible by a service in the cluster with 8080 port and externally 30012.
### Make a deployment of redis pod with 6379 port which is accessible by a service in the cluster with 8081 port and externally 30013.


apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-and-db
  labels:
    deployment: web-and-db
spec:
  replicas: 7
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
        db: redis
    spec:
      containers:
        - name: nginx-container
          image: nginx
          imagePullPolicy: Always
          ports:
            - containerPort: 80

        - name: redis-container
          imagePullPolicy: Always
          image: redis
          ports:
            - containerPort: 6379


---
apiVersion: v1
kind: Service
metadata:
  name: serviceswebdbapp
  labels:
    service: nodeport
spec:
  selector:
    app: webapp
    db: redis
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 30012
      name: web-service

    - name: db-service
      port: 8081
      nodePort: 30013
      targetPort: 6379
  type: NodePort
  clusterIP: 10.96.0.71
