apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: nginx
    app: web-service
    function: front-end
spec:
  containers:
    - name: web
      image: nginx
      ports:
        - containerPort: 8080
  nodeName: node02