

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: affinity1
  labels:
    condition: multiple1
spec:
  replicas: 5
  selector:
    matchLabels:
      dept: SRE
  template:
    metadata:
      labels:
        dept: SRE
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: zone
                    operator: In
                    values:
                      - banani

      containers:
        - name: nginx-container
          image: nginx
          imagePullPolicy: Always
          ports:
            - containerPort: 80



---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: affinity2
  labels:
    condition: multiple2
spec:
  replicas: 5
  selector:
    matchLabels:
      dept: IB
  template:
    metadata:
      labels:
        dept: IB
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - kworker3
              weight: 1
      containers:
        - name: redis-container
          image: redis
          imagePullPolicy: Always
          ports:
            - containerPort: 6379