apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: elasticsearch
  name: elasticsearch
  namespace: elasticsearch
spec:
  selector:
    matchLabels:
      app: elasticsearch
  template:
      metadata:
        labels:
          app: elasticsearch
      spec:
        containers:
          - name: fluentd
            image: registry.k8s.io/fluentd-elasticsearch:1.20
            imagePullPolicy: Always