apiVersion: v1
kind: Service
metadata:
  name: myapp-deployment
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30010
      protocol: tcp
  selector:
    type: front-end