apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc1
  labels:
    app: myapp
    type: front-end
spec:
  template:
    metadata:
      name: myapp-prod
      labels:
        app: myapp
        type: front-prod
    spec:
      containers:
        - name: webpage
          image: nginx

  replicas: 5