


apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeselectordp
  labels:
    scheduling: nodeselector
    category: deployment
spec:
  replicas: 7
  selector:
    matchLabels:
      dept: SRE
  template:
    metadata:
      labels:
        dept: SRE
    spec:
      nodeSelector:
        cpu: high
      containers:
        - name: nginx-container
          image: nginx
          imagePullPolicy: Always
          ports:
            - containerPort: 80

        - name: redis-container
          imagePullPolicy: Always
          image: redis
          ports:
            - containerPort: 6379
