
---
apiVersion: v1
kind: Namespace
metadata:
  name: akdumbakdum


---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: akdumbakdum
  name: nodeselectordp
  labels:
    schedule: nodeseclector
    service: deployment
spec:
  replicas: 7
  selector:
    matchLabels:
      dept: SRE
  template:
    metadata:
      labels:
        dept: SRE
    spec:
      nodeSelector:
        disk: ssd
      containers:
        - name: nginx-container
          image: nginx
          imagePullPolicy: Always
          ports:
            - containerPort: 80

        - name: redis-container
          imagePullPolicy: Always
          image: redis
          ports:
            - containerPort: 6379