apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
    type: front-end
spec:
  selector:
    matchLabels:
      type: app
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: app
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.26.0
  replicas: 8