---
apiVersion: v1
kind: Namespace
metadata:
  name: alhua


---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: alhua
  name: dp-svc-ns
  labels:
    service: clusterip
    namespace: alhua
    dp: "yes"
spec:
  replicas: 7
  selector:
    matchLabels:
      dept: EEE
  template:
    metadata:
      labels:
        dept: EEE
    spec:
      containers:
        - name: nginx-container
          image: nginx
          imagePullPolicy: Always
          ports:
            - containerPort: 80

        - name: redis-container
          imagePullPolicy: Always
          image: redis
          ports:
            - containerPort: 6379


---
apiVersion: v1
kind: Service
metadata:
  name: ext-service
  namespace: alhua
  labels:
    service: external
spec:
  selector:
    dept: EEE
  clusterIP: 10.96.0.10
  type: NodePort
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP
      name: web-port
      nodePort: 30018

    - port: 8081
      targetPort: 6379
      protocol: TCP
      name: redis-port
      nodePort: 30019