apiVersion: apps/v1
kind: Deployment
metadata:
  name: red
spec:
  selector:
    matchLabels:
      run: nginx
  template:
      metadata:
        labels:
          run: nginx
      spec:
        containers:
          - name: nginx
            imagePullPolicy: Always
            image: nginx
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: 
                      operator: