### Make multiple internal services for communicating each others where service port is 8080 and container port 80
### And service port is 9090 and container port 5432


---
apiVersion: v1
kind: Service
metadata:
  name: multiservice
  labels:
    clusterip: multi-ports
spec:
  selector:
    service: internal1
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP
      name: for-8080-port
    - port: 9090
      targetPort: 5432
      protocol: UDP
      name: for-9090-port
  type: ClusterIP
  clusterIP: 10.96.0.71