### Make a Nginx pod with 80 port which is accessible by a service in the cluster with 8081 port

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-service
  labels:
    app: webapp
    network: internal
spec:
  containers:
    - name: nginx-container
      image: nginx
      imagePullPolicy: Always
      ports:
        - containerPort: 80
  restartPolicy: Always



---
apiVersion: v1
kind: Service
metadata:
  name: clusterip-service
  labels:
    service: clsuterip
spec:
  selector:
    network: internal
  type: ClusterIP
  clusterIP: 10.96.0.71
  ports:
    - port: 8081
      targetPort: 80
      protocol: TCP