### Make a Nginx deployment with 80 port which is accessible by a service in the cluster with 8081 port. Cluster IP will be 10.96.0.71.


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-service
  labels:
    app: webapp
    network: internal
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        container: web
    spec:
      containers:
        - name: nginx-container
          imagePullPolicy: Always
          image: nginx
          ports:
            - containerPort: 80


---
apiVersion: v1
kind: Service
metadata:
  name: clusterip-service
  labels:
    service: clsuterip
spec:
  selector:
    app: nginx
    container: web
  ports:
    - port: 8081
      targetPort: 80
      protocol: TCP
  clusterIP: 10.96.0.71
  type: ClusterIP